language: ruby

jobs:
  include:
    - stage: test-2.4
      rvm: 2.4.3
      script:
        - bundle exec rake spec

    - stage: test-2.5
      rvm: 2.5.0
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - bundle exec rake spec
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: tag-new-release-if-applicable
      if: branch = master AND type != pull_request
      before_script:
        - openssl aes-256-cbc -K $encrypted_bfd358de8814_key -iv $encrypted_bfd358de8814_iv -in ./ci-helpers/atomic_cache_deploy.enc -out atomic_cache_deploy -d
        - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - chmod 600 atomic_cache_deploy
        - mv atomic_cache_deploy ~/.ssh/id_rsa
        - git config --global user.email "deploy-bot@ibotta.com"
        - git config --global user.name "Deploy Bot"
        - git remote add deploy ssh://git@github.com/Ibotta/atomic_cache.git
      script:
        - ./ci-helpers/gem_helper tag_new_release_if_applicable

    - stage: publish-gem
      if: tag =~ ^v # tags starting with "v" represent releases (as in v0.1.0)
      script:
        - ./ci-helpers/gem_helper publish
